name: Auto-merge safe dependencies
on:
  pull_request:
    types: [labeled, synchronize]
jobs:
  auto-merge:
    if: contains(github.event.pull_request.labels.*.name, 'dependencies')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request
            const title = pr.title.toLowerCase()
            const isSafe = /\b(chore|deps|dependencies)\b/.test(title) && !title.includes('major')
            if (isSafe) {
              github.rest.pulls.merge({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pr.number,
                merge_method: 'squash'
              })
            }
